name: 'Test'

on:
  # Trigger manually
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run action
        id: download-public
        uses: robinraju/release-downloader@62d3e983c99c16718304fb1a69553f01b84b0d40
        with:
          repository: 'ryanoasis/nerd-fonts'
          tag: v2.2.2
          fileName: 'FontPatcher.zip'
          out-file-path: './test-downloads'

      - name: List downloaded files
        shell: bash
        run: ls -lrth test-downloads

      - name: Read output variable set by previous steps
        shell: bash
        run: |
          if [ -n ${{steps.download-public.outputs.tag_name}} ]; then
            echo ${{steps.download-public.outputs.tag_name}}
          else
            echo "Unable to read output variable from step download-public"
            exit 1
          fi
